version: '3.0'

services:
  frontend:
    platform: linux/x86_64
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    depends_on:
      - backend

  backend:
    platform: linux/x86_64
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: &db_username "postgres"
      SPRING_DATASOURCE_PASSWORD: &db_password "postgres"

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: *db_username
      POSTGRES_PASSWORD: *db_password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
