version: '3.4'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: &db_username "postgres"
      SPRING_DATASOURCE_PASSWORD: &db_password "postgres"

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: *db_username
      POSTGRES_PASSWORD: *db_password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

#version: '3'
#
#services:
#  webapp:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/chicago_plays
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#
#  db:
#    image: postgres:13
#    environment:
#      - POSTGRES_DB=chicago_plays
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#
#volumes:
#  pgdata: