DROP TABLE genres CASCADE;
DROP TABLE events CASCADE;
DROP TABLE IF EXISTS genres_events;

CREATE TABLE events
(
    event_id    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       varchar,
--     first_date  timestamp,
--     last_date   timestamp,
    theatre     varchar,
    description varchar,
    event_url   varchar,
    min_price   int,
    max_price   int
--     nextShow    int
);

INSERT INTO events (title, theatre, description, event_url, min_price, max_price)
VALUES ('Big Fish', 'Marriott Theatre', 'Dream, Live, Love... Bigger!

A fantastical musical adventure inspired by a father’s incredible stories. Based on the celebrated novel by Daniel Wallace and the acclaimed film directed by Tim …',
        'https://chicagoplays.com/event/big-fish/', 0, 0);

INSERT INTO events(title, theatre, description, event_url, min_price, max_price) VALUES ('The Christians', 'Citadel Theatre Company', 'The Christians by Lucas Hnath, directed by Scott Westerman, runs February 10th through March 12th, 2023.

Synopsis: Twenty years ago, Pastor Paul’s church was nothing more than a modest …', 'https://chicagoplays.com/event/the-christians/', 15, 45);

CREATE TABLE genres
(
    genre_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre    varchar UNIQUE
);

CREATE TABLE genres_events
(
    genre_id int REFERENCES genres (genre_id),
    event_id int REFERENCES events (event_id),
    PRIMARY KEY (genre_id, event_id)
);