DROP TABLE IF EXISTS events;

CREATE TABLE events
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR,
    runs        VARCHAR,
    firstDate   TIMESTAMP,
    lastDate    TIMESTAMP,
    theatre     VARCHAR,
    genres      VARCHAR,
    description VARCHAR,
    eventUrl    VARCHAR,
    minPrice    INTEGER,
    maxPrice    INTEGER,
    nextShow    TIMESTAMP
);