apiVersion: v1
kind: Service
metadata:
  labels:
    io.service: frontend
  name: frontend
spec:
  ports:
    - protocol: TCP
      port: 3000  # Port exposed by the service
      targetPort: 8080  # Port on which the container is listening
  selector:
    io.service: frontend
status:
  loadBalancer: {}
