apiVersion: v1
kind: Service
metadata:
  labels:
    io.service: frontend
  name: frontend
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 8080
  selector:
    io.service: frontend
status:
  loadBalancer: {}
