apiVersion: v1
kind: Pod
metadata:
  name: pg-client
spec:
  containers:
  - name: pg-client
    image: postgres:latest
    command: ["tail", "-f", "/dev/null"]  # Keeps the container running
    env:
      - name: SPRING_DATASOURCE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: chicago-plays-db-secret
            key: SPRING_DATASOURCE_PASSWORD
      - name: SPRING_DATASOURCE_URL
        valueFrom:
          secretKeyRef:
            name: chicago-plays-db-secret
            key: SPRING_DATASOURCE_URL
  volumes:
    - name: sql-secret-volume
      secret:
        secretName: chicago-plays-db-secret